const baseCards = [
  ["1101", "Hydrogen", "H", "Alpha", "Omicron", "Omea"],
  ["1102", "Helium", "He", "Alpha", "Omicron", "Omea"],
  ["1103", "Lithium", "Li", "Alpha", "Omicron", "Omea"],
  ["1104", "Beryllium", "Be", "Alpha", "Omicron", "Omea"],
  ["1105", "Boron", "B", "Alpha", "Omicron", "Omea"],
  ["1106", "Carbon", "C", "Alpha", "Omicron", "Omea"],
  ["1107", "Nitrogen", "N", "Alpha", "Omicron", "Omea"],
  ["1108", "Oxygen", "O", "Alpha", "Omicron", "Omea"],
  ["1109", "Fluorine", "F", "Alpha", "Omicron", "Omea"],
  ["1110", "Neon", "Ne", "Alpha", "Omicron", "Omea"],
  ["1111", "Sodium", "Na", "Alpha", "Omicron", "Omea"],
  ["1112", "Magnesium", "Mg", "Alpha", "Omicron", "Omea"],
  ["1113", "Aluminium", "Al", "Alpha", "Omicron", "Omea"],
  ["1114", "Silicon", "Si", "Alpha", "Omicron", "Omea"],
  ["1115", "Phosphorus", "P", "Alpha", "Omicron", "Omea"],
  ["1116", "Sulfur", "S", "Alpha", "Omicron", "Omea"],
  ["1117", "Chlorine", "Cl", "Alpha", "Omicron", "Omea"],
  ["1118", "Argon", "Ar", "Alpha", "Omicron", "Omea"],
  ["1119", "Calcium", "Ca", "Alpha", "Omicron", "Omea"],
  ["1120", "Scandium", "Sc", "Alpha", "Omicron", "Omea"],
  ["1121", "Titanium", "Ti", "Alpha", "Omicron", "Omea"],
  ["1122", "Vanadium", "V", "Alpha", "Omicron", "Omea"],
  ["1123", "Chromium", "Cr", "Alpha", "Omicron", "Omea"],
  ["1124", "Manganese", "Mn", "Alpha", "Omicron", "Omea"],
  ["1125", "Cobalt", "Co", "Alpha", "Omicron", "Omea"],
  ["1126", "Nickel", "Ni", "Alpha", "Omicron", "Omea"],
  ["1127", "Copper", "Cu", "Alpha", "Omicron", "Omea"],
  ["1128", "Zinc", "Zn", "Alpha", "Omicron", "Omea"],
  ["1129", "Gallium", "Ga", "Alpha", "Omicron", "Omea"],
  ["1130", "Germanium", "Ge", "Alpha", "Omicron", "Omea"],
  ["1131", "Arsenic", "As", "Alpha", "Omicron", "Omea"],
  ["1132", "Selenium", "Se", "Alpha", "Omicron", "Omea"],
  ["1133", "Bromine", "Br", "Alpha", "Omicron", "Omea"],
  ["1134", "Krypton", "Kr", "Alpha", "Omicron", "Omea"],
  ["1135", "Rubidium", "Rb", "Alpha", "Omicron", "Omea"],
  ["1136", "Strontium", "Sr", "Alpha", "Omicron", "Omea"],
  ["1137", "Yttrium", "Y", "Alpha", "Omicron", "Omea"],
  ["1138", "Zirconium", "Zr", "Alpha", "Omicron", "Omea"],
  ["1139", "Niobium", "Nb", "Alpha", "Omicron", "Omea"],
  ["1140", "Molybdenum", "Mo", "Alpha", "Omicron", "Omea"],
  ["1141", "Technetium", "Tc", "Alpha", "Omicron", "Omea"],
  ["1142", "Ruthenium", "Ru", "Alpha", "Omicron", "Omea"],
  ["1143", "Rhodium", "Rh", "Alpha", "Omicron", "Omea"],
  ["1144", "Palladium", "Pd", "Alpha", "Omicron", "Omea"],
  ["1145", "Cadmium", "Cd", "Alpha", "Omicron", "Omea"],
  ["1146", "Indium", "In", "Alpha", "Omicron", "Omea"],
  ["1147", "Antimony", "Sb", "Alpha", "Omicron", "Omea"],
  ["1148", "Tellurium", "Te", "Alpha", "Omicron", "Omea"],
  ["1149", "Iodine", "I", "Alpha", "Omicron", "Omea"],
  ["1150", "Xenon", "Xe", "Alpha", "Omicron", "Omea"],
  ["1151", "Caesium", "Cs", "Alpha", "Omicron", "Omea"],
  ["1152", "Barium", "Ba", "Alpha", "Omicron", "Omea"],
  ["1153", "Lanthanum", "La", "Alpha", "Omicron", "Omea"],
  ["1154", "Cerium", "Ce", "Alpha", "Omicron", "Omea"],
  ["1155", "Praseodymium", "Pr", "Alpha", "Omicron", "Omea"],
  ["1156", "Neodymium", "Nd", "Alpha", "Omicron", "Omea"],
  ["1157", "Promethium", "Pm", "Alpha", "Omicron", "Omea"],
  ["1158", "Samarium", "Sm", "Alpha", "Omicron", "Omea"],
  ["1159", "Europium", "Eu", "Alpha", "Omicron", "Omea"],
  ["1160", "Gadolinium", "Gd", "Alpha", "Omicron", "Omea"],
  ["1161", "Terbium", "Tb", "Alpha", "Omicron", "Omea"],
  ["1162", "Dysprosium", "Dy", "Alpha", "Omicron", "Omea"],
  ["1163", "Holmium", "Ho", "Alpha", "Omicron", "Omea"],
  ["1164", "Erbium", "Er", "Alpha", "Omicron", "Omea"],
  ["1165", "Thulium", "Tm", "Alpha", "Omicron", "Omea"],
  ["1166", "Ytterbium", "Yb", "Alpha", "Omicron", "Omea"],
  ["1167", "Lutetium", "Lu", "Alpha", "Omicron", "Omea"],
  ["1168", "Hafnium", "Hf", "Alpha", "Omicron", "Omea"],
  ["1169", "Tantalum", "Ta", "Alpha", "Omicron", "Omea"],
  ["1170", "Rhenium", "Re", "Alpha", "Omicron", "Omea"],
  ["1171", "Osmium", "Os", "Alpha", "Omicron", "Omea"],
  ["1172", "Iridium", "Ir", "Alpha", "Omicron", "Omea"],
  ["1173", "Platinum", "Pt", "Alpha", "Omicron", "Omea"],
  ["1174", "Thallium", "Tl", "Alpha", "Omicron", "Omea"],
];

const flashcardData = baseCards.map(
  ([cardNumber, question, answer, distractor1, distractor2, distractor3]) => ({
    cardNumber: Number(cardNumber),
    question,
    answer,
    distractor1,
    distractor2,
    distractor3,
  }),
);

export default flashcardData;
