const baseCards = [
  ["1201", "What is the primary purpose of using a 3-character 'alpha code' during product searches in Eclipse?", "To filter or narrow search results and reduce mistakes.", "To increase the selling price automatically.", "To limit results to a specific manufacturer pricing structure.", "To activate advanced inventory replenishment logic."],
  ["1202", "How many characters long is the standard alpha code used for filtering Price Lines in Eclipse?", "Three characters", "Four characters", "Two characters plus a numeric suffix.", "A variable length depending on the vendor."],
  ["1203", "Which specific Price Line code is the exception to the standard three-character length rule?", "NONSTOCK", "STK", "NST", "NSK"],
  ["1204", "What action should an employee take if they are in doubt about which Price Line to use for an item?", "Check the item master or ask the purchasing department.", "Assign any similar alpha code at random.", "Use the most commonly used alpha code in the branch.", "Default to the vendor abbreviation in the description."],
  ["1205", "In Eclipse, the _____ is a 3-character identifier used as a filter field to quickly find specific groups of products.", "alpha code", "product key", "price identifier", "vendor class code"],
  ["1206", "What does alpha code COP represent?", "Definition: Commodity copper building wire and cable used for circuits, feeders, and grounding.", "Copper conduit fittings.", "Commodity copper conductors used for power and grounding.", "Copper-clad aluminum grounding electrodes."],
  ["1207", "Which alpha code should be used to filter for Siemens grid and power transmission technology like transformers and switchgear?", "SIE", "SEM", "SIM", "SNS"],
  ["1208", "Code: CPS", "Definition: Medium-voltage distribution and utility equipment including Cooper Power series components.", "Copper power supplies.", "Cooper Power Systems utility distribution equipment.", "Control power switching assemblies."],
  ["1209", "Which alpha code represents commodity aluminum building wire used for feeders and service entrance applications?", "ALU", "ALM", "AUL", "ALX"],
  ["1210", "What is the purpose of the NONSTOCK price line?", "It serves as a catch-all for special-order or non-catalog items not tied to a standard manufacturer.", "Items temporarily out of stock.", "Special procurement items not tied to standard vendor catalogs.", "Inventory reserved for internal branch use only."],
  ["1211", "What does alpha code SQD represent?", "Definition: Square D electrical distribution and control products like circuit breakers and panelboards.", "Square conduit fittings.", "Square D power distribution equipment and controls.", "Service entrance disconnect assemblies."],
  ["1212", "What products are categorized under the PVC price line?", "Commodity PVC conduit and matching fittings for raceway protection.", "PVC electrical tape.", "PVC conduit and related raceway fittings.", "PVC-jacketed underground feeder cable."],
  ["1213", "Which alpha code is used for Eiko commercial and industrial lighting products, including LED lamps and fixtures?", "EIK", "EKO", "EIO", "EIX"],
  ["1214", "Code: MIL", "Definition: Milbank metering equipment, enclosures, and related power distribution accessories.", "Military-grade connectors.", "Milbank meter sockets and enclosure systems.", "Meter interface load centers."],
  ["1215", "Which alpha code is designated for Appleton hazardous location products and explosionproof fittings?", "APP", "APL", "APT", "APN"],
  ["1216", "What does alpha code PSI represent?", "Definition: Pass & Seymour (Legrand) wiring devices such as switches, receptacles, and wall plates.", "Pressure sensing instruments.", "Pass & Seymour wiring devices and accessories.", "Power system interface modules."],
  ["1217", "What is the alpha code for commodity thinwall steel conduit used for interior raceway runs?", "EMT", "EMC", "ENT", "ETM"],
  ["1218", "Code: FIT", "Definition: Commodity conduit fittings and connectors like couplings, straps, and bushings.", "Fiber optic terminations.", "Standard conduit fittings and installation hardware.", "Field installation tools."],
  ["1219", "Which alpha code is used for rigid galvanized steel conduit intended for heavy-wall outdoor applications?", "GRC", "RGC", "GAL", "RGS"],
  ["1220", "What does alpha code RAC represent?", "Definition: RACO (Hubbell) electrical boxes, covers, and fittings made of steel or nonmetallic materials.", "Raceway assemblies.", "RACO brand electrical boxes and accessories.", "Rigid aluminum conduit systems."],
  ["1221", "Which alpha code specifically filters for Metalux (Cooper) commercial lighting fixtures like LED troffers and panels?", "MEX", "MET", "MXL", "MEL"],
  ["1222", "Code: CLG", "Definition: Cooper Lighting Group’s broad portfolio of luminaires and lighting controls across multiple brands.", "Ceiling grid components.", "Cooper Lighting Group luminaires and control systems.", "Commercial lighting general category."],
  ["1223", "Which alpha code represents FCI Burndy products like lugs, splices, and grounding hardware?", "BUR", "BRD", "BND", "BYR"],
  ["1224", "What does alpha code POS represent?", "Definition: Power-Strut metal framing systems used to support conduit, panels, and lighting.", "Point of sale equipment.", "Power-Strut structural support framing systems.", "Panel mounting support brackets."],
  ["1225", "Which alpha code is used for Barron Lighting commercial and architectural products, including exit signs and emergency units?", "BAR", "BRN", "BAL", "BOR"],
  ["1226", "Code: CAD", "Definition: nVent CADDY (Erico) fastening and support products such as clamps and hangers.", "Computer-aided design software.", "nVent CADDY fastening and support solutions.", "Conduit attachment devices."],
  ["1227", "Which alpha code identifies Mersen Ferraz Shawmut circuit protection products like fuses and fuse holders?", "FRZ", "FER", "FSH", "MRS"],
  ["1228", "What does alpha code IDI represent?", "Definition: IDEAL Industries installation consumables including wire connectors, lubricant, and testers.", "Industrial data interface.", "IDEAL Industries installation and wiring consumables.", "Insulation diagnostic instruments."],
  ["1229", "Which alpha code is used for Atlas commercial and industrial LED lighting fixtures for both indoor and outdoor use?", "ATL", "ATX", "ALS", "ATF"],
  ["1230", "Code: WIE", "Definition: Wiegmann electrical enclosures, junction boxes, and NEMA-rated steel cabinets.", "Wiring interface equipment.", "Wiegmann electrical enclosures and cabinets.", "Weatherproof industrial enclosures."],
  ["1231", "Which alpha code is designated for professional electrician tools like pliers, fish tapes, and tool storage from Klein Tools?", "KLN", "KLE", "KLT", "KLTN"],
  ["1232", "What is the primary use of the BRB (Breaker Breaker) price line?", "It is used for aftermarket, surplus, or obsolete circuit breakers and related gear.", "Brand-new circuit breakers only.", "Aftermarket and surplus breaker inventory.", "Breaker repair components exclusively."],
  ["1233", "What does alpha code ARL represent?", "Definition: Arlington electrical fittings and connectors used for various installation accessories.", "Alarm relays.", "Arlington electrical fittings and mounting accessories.", "Architectural lighting assemblies."],
  ["1234", "Which alpha code should be used for PVC-coated rigid conduit systems designed for corrosive environments?", "CAL", "PVC", "PCR", "CPV"],
  ["1235", "Code: HAL", "Definition: Halo (Cooper Lighting) recessed and downlighting solutions, including track and surface lighting.", "Halogen lamps.", "Halo recessed and architectural lighting products.", "High-ambient luminaires."],
  ["1236", "How is the RSK alpha code unique compared to most other price lines in the spreadsheet?", "It represents a manufacturers representative agency rather than a single manufacturer of products.", "It is used only for discontinued products.", "It identifies a representative agency rather than a single product manufacturer.", "It serves as a regional warehouse grouping code."],
  ["1237", "What does alpha code SRL represent?", "Definition: Sure-Lites exit signs, emergency drivers, and egress lighting accessories.", "Structural relay logic.", "Sure-Lites emergency and exit lighting systems.", "Safety rated luminaires."],
  ["1238", "Which alpha code is used for Lumark (Cooper Lighting) outdoor and area lighting solutions like flood and site lighting?", "LUM", "LUK", "LMK", "LMA"],
  ["1239", "Code: SYL", "Definition: Sylvania Osram lighting products including LED lamps, bulbs, and fixtures.", "System lighting category.", "Sylvania lighting lamps and fixtures.", "Synthetic luminaires."],
  ["1240", "Which alpha code represents Hammond Power Solutions dry-type transformers?", "HMT", "HMD", "HPS", "HMP"],
  ["1241", "What does alpha code GRD represent?", "Definition: Ground rods and grounding hardware such as electrodes, clamps, and drive heads.", "Grid equipment.", "Grounding electrodes and related hardware.", "Generator distribution components."],
  ["1242", "Which alpha code is used for Selecta Products, a master distributor that consolidates multiple brands like fasteners and tapes?", "SES", "SEL", "SLT", "SEC"],
  ["1243", "Code: TPZ", "Definition: Topaz electrical fittings, connectors, boxes, and conduit accessories.", "Temporary power zones.", "Topaz conduit fittings and accessories.", "Terminal protection zones."],
  ["1244", "Which alpha code is used for rigid aluminum conduit used for corrosion resistance and lighter weight?", "ARC", "ALC", "ALR", "RAC"],
  ["1245", "What does alpha code HUB represent?", "Definition: Hubbell Wiring Device-Kellems products including receptacles, plugs, and cable grips.", "Hub assemblies.", "Hubbell wiring devices and connectivity products.", "High utility breakers."],
  ["1246", "Which alpha code is designated for Holophane commercial and industrial lighting systems for demanding environments?", "HPN", "HOL", "HLP", "HPH"],
  ["1247", "Code: WIR", "Definition: Wiremold (Legrand) surface raceway, floor boxes, and cable management systems.", "Wiring harnesses.", "Wiremold surface raceway and cable management products.", "Wire insulation repair kits."],
  ["1248", "Which alpha code is used for All Current Electric products including grounding and power distribution components?", "ACU", "ALL", "ACE", "ACL"],
  ["1249", "What does alpha code MMM represent?", "Definition: 3M electrical products such as tapes, splicing kits, and insulation materials.", "Multiple manufacturer misc.", "3M electrical tapes and connection products.", "Main material management grouping."],
  ["1250", "Which alpha code is used for Norberg IES, a specialty supplier focused on fuses and hazardous-location controls?", "NBI", "NOR", "NBG", "NBS"],
  ["1251", "Code: SCE", "Definition: Saginaw Control and Engineering electrical enclosures and wall-mount cabinets.", "Service control enclosures.", "Saginaw Control and Engineering enclosure systems.", "Secondary containment enclosures."],
  ["1252", "Which alpha code is used for Quazite (Hubbell) underground utility enclosures and polymer concrete boxes?", "QZS", "QUA", "QZT", "QZE"],
  ["1253", "What does alpha code CDW represent?", "Definition: nVent ERICO Cadweld exothermic welding systems for permanent electrical ground connections.", "Cold welded connectors.", "Cadweld grounding and bonding systems.", "Cable distribution weld assemblies."],
  ["1254", "Which alpha code represents Cablofil wire mesh cable tray systems?", "CAB", "CBL", "CBF", "CFT"],
  
  
];

const flashcardData = baseCards.map(
  ([cardNumber, question, answer, distractor1, distractor2, distractor3]) => ({
    cardNumber: Number(cardNumber),
    question,
    answer,
    distractor1,
    distractor2,
    distractor3,
  }),
);

export default flashcardData;
